nelmio_api_doc:
    documentation:
        info:
            title: Book API 
            description: La collection complète de tes livres préférés accessible gratuitement !
            version: 1.2.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
